config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/freshuser', to: 'home#freshuser'
  get '/developer', to: 'home#developer'
  get '/search', to: 'home#search'
  get '/administer_families', to: 'home#administer_families'
  
  resources :families, except: [:destroy] do
    resources :parents, only: [:new, :create, :edit, :update]
    resources :students, only: [:new, :create, :edit, :update]
    resources :contacts, only: [:new, :create]
    resources :addresses, only: [:new, :create]

    collection do
      get "search"
    end
  end

  resources :parents, except: [:destroy, :new, :create] do
    resources :addresses, only: [:new, :create]
    resources :contacts, only: [:new, :create]

    collection do
      get "search"
    end
  end

  resources :contacts, only: [:edit, :update]
  resources :addresses, only: [:edit, :update]

  resources :students, except: [:destroy, :new, :create] do
    collection do
      get "search"
    end
  end

  resources :schoolclasses, except: [:destroy] do
    member do
      get "add_teachers"
      get "add_students"
      post "set_teachers"
      post "set_students"
    end
  end

  resources :teachers, except: [:destroy]

  resources :users, only: [:new, :show, :edit, :create, :update] do
    collection do
      get "admin_edit"
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_user, except: [:index, :developer]

  # this is here so that we can present some basic "about this application"
  # information about the PTA directory
  
  def index
    if logged_in?
      redirect_from_root_for_logged_in
    end
  end

  def freshuser
  end

  def search

    @search_results = []
    
    if params[:search]
      # here we are looking for almost any string among our data set

      search_classes = [Family, Parent, Student, Teacher, Schoolclass, Address, Contact]

      unfolded_search_results = search_classes.inject([]) { |memo, directory_class| memo + directory_class.search_for(params[:search]) }

      # we need to treat contacts and addresses as special.
      # what we do is "fold" the results of addresses to match against the
      # addressable family or parent
      # and similarly contacts fold to teachers or parents
      folded_search_results = fold_search_results_for_contacts_and_addresses(unfolded_search_results)


      # see if we can order the results somehow
      @search_results = []
      
      folded_search_results.each do |s|
        case
        when s.class == Family
          @search_results << [s.name, "Family", icon_action_link("icon-book", "Details", family_path(s))]
        
        when s.class == Parent
          @search_results << [s.last_first, "Parent", icon_action_link("icon-user", "Details", parent_path(s))]
        
        when s.class == Student
          @search_results << [s.last_first, "Student", icon_action_link("icon-user", "Details", student_path(s))]
        
        when s.class == Teacher
          @search_results << [s.last_first, "Teacher", icon_action_link("icon-user", "Details", teacher_path(s))]

        when s.class == Schoolclass
          @search_results << [s.name, "Class", icon_action_link("icon-list", "Details", schoolclass_path(s))]
        end

        @search_results.sort! do |x,y|
          retval = x[1] <=> y[1]
          retval == 0 ? x[0] <=> y[0] : retval
        end

      end # iterate over folded search results
    end # params specified a search
  end

  def developer
  end

  def administer_families
  end

  private

  def fold_search_results_for_contacts_and_addresses(search_results)
    
    search_set = Set.new

    search_results.each do |entry|
      if (entry.class == Address)
        search_set << entry.addressable
      elsif (entry.class ==  Contact)
        search_set << entry.contactable
      else
        search_set << entry
      end
    end

    # return an array form of the set
    search_set.to_a

  end

end

app/views/home/_search_results.html.haml
%div
  %table{class: "table table-condensed table-striped table-bordered", style: "background-color: #CCFFFF"}
    %tr{style: "font-size: 18px"}
      %th
        Record
      %th
        Type
      %th{style: "text-align: center"}
        Actions

    - search_results_list.each do |s|
      %tr
        %td= s[0]
        %td= s[1]
        %td= s[2]

app/views/home/administer_families.html.erb
<%= render "families/family_list", family_list: current_user_get.families %>

app/views/home/developer.html.erb
<div class="well">
  <h3><em>Basic business rules to help you navigate the application:</em></h3>

  <h4>4 Key models</h4>
  
  <ul>
    <li style="font-size: 18px; padding-bottom: 4px;">Families</li>
    <li style="font-size: 18px; padding-bottom: 4px;">Parents</li>
    <li style="font-size: 18px; padding-bottom: 4px;">Students</li>
    <li style="font-size: 18px; padding-bottom: 4px;">Teachers</li>
  </ul>

  <hr/>
  <ul>
    <li style="font-size: 18px; padding-bottom: 8px;"><em><strong>Families</strong></em> contain multiple Parents (1:M), an optional address (1:1), and multiple Students (1:M).  A family belongs to a <em><strong>User</strong></em>.  Only the user to who the family belongs (or an admin or superadmin) can edit information for the family (including the parents and students within the family).</li>

    <li style="font-size: 18px; padding-bottom: 8px;"><em><strong>Parents</strong></em> belong to families(M:1) and contain an optional address (1:1), and multiple pieces of contact information (1:M)
    <li style="font-size: 18px; padding-bottom: 8px;"><em><strong>Students</strong></em> belong to families (M:1) and are associated with classes (M:M).  A student record can be modified by the "creator" of the Family that a student belongs to, or by an admin or superadmin.</li>
    <li style="font-size: 18px; padding-bottom: 8px;"><em><strong>Teachers</strong></em> can contain multiple pieces of contact information, and are associated with Classes (M:M association).  Only an Admin or Superadmin user can edit Teacher records.</li>
  </ul>

  <hr/>
  <h4>3 Subordinate models</h4>
  <ul>
    <li style="font-size: 18px; padding-bottom: 8px;">
      <em><strong>Classes</strong></em> (model is called Schoolclasses to avoid the reserved word class) form M:M association between students and teachers.  Only an Admin or Superadmin user can create Class records, although any user can add/remove students from a particular class for the families that the user manages.
    </li>
    <li style="font-size: 18px; padding-bottom: 8px;">
      <em><strong>Addresses</strong></em> are polymorphic associations that can belong to addressables (Families or Parents).
    </li>
    <li style="font-size: 18px; padding-bottom: 8px;">
      <em><strong>Contacts</strong></em> are polymorphic associations that can belong to contactable (Parents or Teachers).
    </li>
  </ul>

  <p>Only registered users have access to the contents of the app.</p>

  <p>Registered users can search (but not edit) all data including Families, Parents, Students, teachers.</p>

  <p>Every family has an "family_administator" user (the user who created the family record) who can edit any of the information in the "tree" of the family data (the family itself, family address, parents beloning to the family, students belonging to the family, and contact and address information for the parents)</p>

  <p>To test out Admin and Superadmin functionality, I have created the following accounts already in the system: <strong>admin</strong>, password "pass" and <strong>superadmin</strong> password "pass"</p>
</div>

app/views/home/freshuser.html.erb
<h2>Up and Running with PTA Directory</h2>

<div class="well">
  <h3>Getting Started is Easy:</h3>

  <div class="well">
    <ul>
      <li style="font-size: 22px; padding-bottom: 8px;">Create your own Family record</li>
      <ul style="font-size: 18px; padding-bottom: 6px;">
        <li style="padding-bottom: 2px;">Click on the "Create New Family" button in the navigation bar</li>
        <li style="padding-bottom: 2px;">You will be asked to enter a family name</li>
        <li style="padding-bottom: 2px;">You can then create information on the parents in this family, including their contact information.</li>
          <ul><li style="padding-bottom: 2px;">You can specify a family address for the entire family, or separate addresses for each parent if they are not living together.</li></ul>
        <li style="padding-bottom: 2px;">Then add information about the students in this family: their names and the classes they attend.</li>
      </ul>

      <li style="font-size: 22px; padding-bottom: 6px;">Browse Data</li>
      <ul style="font-size: 18px; padding-bottom: 6px;">
        <li style="padding-bottom: 2px;">Click on the Family Directory in the navigation bar to get a listing of all families</li>
        <li style="padding-bottom: 2px;">Click on the Directory Listings button to get access to lists of</li>
        <ul>
          <li style="padding-bottom: 1px;">Families</li>
          <li style="padding-bottom: 1px;">Parents</li>
          <li style="padding-bottom: 1px;">Students</li>
          <li style="padding-bottom: 1px;">Classes</li>
          <li style="padding-bottom: 1px;">Teachers</li>
        </ul>
        <li style="padding-bottom: 2px;">Navigation is easy: class details link to individual students and teachers, student records lead to classes and families, etc.</li>
      </ul>
      <li style="font-size: 22px; padding-bottom: 6px;">Open Text Search through all of the data</li>
    </ul>
  </div>

  <div class="well">
    <h3>What do you want to do?</h3>
    <% if current_user_get && current_user_get.families.size == 0 %>
      <%= link_to "Create a Family Record", new_family_path, class: "btn btn-primary btn-large", style: "font-size: 32px; margin-top: 8px; margin-left: 40px; padding-left: 20px; padding-top: 20px; padding-bottom: 20px; padding-right: 20px; " %>
    <% else %>
      <%= link_to "View Your #{"Family".pluralize(current_user_get.families.size)}", administer_families_path, class: "btn btn-primary btn-large", style: "font-size: 32px; margin-top: 8px; margin-left: 40px; padding-left: 20px; padding-top: 20px; padding-bottom: 20px; padding-right: 20px; " %>
    <% end %>
    <%= link_to "Search", search_path, class: "btn btn-info btn-large", style: "font-size: 32px; padding-left: 20px; padding-top: 20px; padding-bottom: 20px; padding-right: 20px; margin-top: 8px; margin-left: 40px;" %>
  </div>
  <div class="well">
    <%= link_to "For Tealeaf Students and TAs", developer_path, class: "btn btn-info btn-large", style: "font-size: 18px; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px; margin-top: 10px; margin-left: 10px;" %>

  </div>
</div>

app/views/home/index.html.erb
<div class="container-fluid">

  <h1>PTA Directory</h1>

  <!-- Create some basic information about this app -->

  <div class="row" style="padding-top: 60px;">
    <img src="family2.jpg" class="img-responsive pull-left" alt="Responsive image" style="width:200px;height:200px;padding-right: 40px;"></img>
    <h2 class="pull-right" style="padding-left: 40px;">For Parents</h2>
    <p style="font-size: 24px;"> Create and manage your family including address and contact information for parents, and classes and siblings for your children. 
    </p>
    <ul style="font-size: 20px; padding-top: 40px;">
      <li>View information on other families in your school and their contact information.</li>
      <li>Parents, addresses, phone and email contacts</li>
      <li>See your child's classes, with information on students in each class</li>
    </ul>
  </div>
  <hr/>

  <div class="row">
    <img src="classroom1.jpg" class="img-responsive pull-left" alt="Responsive image" style="width:200px;height:200px;padding-right: 40px;"></img>
    <h2 class="pull-right" style="padding-left: 40px;">For Teachers</h2>
    <p style="font-size: 24px;"> Create and manage classes.</p>
    <ul style="font-size: 20px; padding-top: 40px;">
      <li>View information on your classes and students in your class.</li>
      <li>Access contact information for students' parents.</li>
    </ul>
  </div>
  <hr/>

  <div class="row">
    <%= link_to "Register", register_path, class: "btn btn-large", style: "font-size: 36px; margin-top: 40px; margin-left: 40px; padding-left: 20px; padding-top: 20px; padding-bottom: 20px; padding-right: 20px; " %>
    <%= link_to "Sign In", login_path, class: "btn btn-success btn-large", style: "font-size: 36px; padding-left: 20px; padding-top: 20px; padding-bottom: 20px; padding-right: 20px; margin-top: 40px; margin-left: 40px;" %>

    <%= link_to "For Tealeaf Students and TAs", developer_path, class: "btn btn-info btn-large", style: "font-size: 24px; padding-left: 20px; padding-top: 20px; padding-bottom: 20px; padding-right: 20px; margin-top: 40px; margin-left: 40px;" %>
  </div>

</div>

app/views/home/search.html.erb
<%= render "shared/content_title", title_var: "Open Search in PTA Directory" %>

<!-- Create a search form where you can type in any string and -->
<!-- we will search among all of the items of data for it -->
<div class="well">

  <%= form_tag(search_path, :method => "get", class: "form") do %>
    <div class="control-group">
      <%= label_tag(:search, "Search For:") %>

      <!-- adding support for placeholder text in the field rather than -->
      <!-- explicitly setting field contents -->
      <!-- very strange behavior!  The focus seems only set the second time the page is visited!!! -->
      <% if params[:search] %>
        <%= text_field_tag(:search, params[:search], {autofocus: "autofocus", style: "width: 50em; max-width: 90%;"}) %>
      <% else %>
        <%= text_field_tag(:search, nil, {placeholder: "<Any string in families, teachers, etc.>", autofocus: "autofocus", style: "width: 50em; max-width: 90%;"}) %>
      <% end %>
    </div>

    <br>
    <%= submit_tag("Search", style: "btn btn-primary") %>
  <% end %>

  <!-- we may already have search results, so display them here -->
  <hr/>

  <% if (params[:search] && (params[:search].size > 0)) %>
    <!-- this is a hint that a search has occurred -->
    <!-- now we have to figure out whether any results matched our query -->
    <% if @search_results.size == 0 %>
      <!-- no results match, so give feedback that we DID do a search but nothing was found -->
      <h4>Nothing matches your search criteria</h4>
    <% else %>
      <h4><%= "#{@search_results.size} " + "entry".pluralize(@search_results.size) + " found." %></h4>

      <%= render "home/search_results", search_results_list: @search_results %>
    <% end %>

  <% end %>
</div>