config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/freshuser', to: 'home#freshuser'
  get '/developer', to: 'home#developer'
  get '/search', to: 'home#search'
  get '/administer_families', to: 'home#administer_families'
  
  resources :families, except: [:destroy] do
    resources :parents, only: [:new, :create, :edit, :update]
    resources :students, only: [:new, :create, :edit, :update]
    resources :contacts, only: [:new, :create]
    resources :addresses, only: [:new, :create]

    collection do
      get "search"
    end
  end

  resources :parents, except: [:destroy, :new, :create] do
    resources :addresses, only: [:new, :create]
    resources :contacts, only: [:new, :create]

    collection do
      get "search"
    end
  end

  resources :contacts, only: [:edit, :update]
  resources :addresses, only: [:edit, :update]

  resources :students, except: [:destroy, :new, :create] do
    collection do
      get "search"
    end
  end

  resources :schoolclasses, except: [:destroy] do
    member do
      get "add_teachers"
      get "add_students"
      post "set_teachers"
      post "set_students"
    end
  end

  resources :teachers, except: [:destroy]

  resources :users, only: [:new, :show, :edit, :create, :update] do
    collection do
      get "admin_edit"
    end
  end

end

app/models/family.rb
class Family < ActiveRecord::Base

  include Searchable

  has_many    :parents
  has_many    :students
  has_one     :address, as: :addressable
  belongs_to  :family_administrator, foreign_key: 'user_id', class_name: 'User'

  validates   :name, presence: true

  def get_administrator
    # what user ID is allowed to administer (edit) this object
    self.family_administrator
  end

end


app/models/student.rb
class Student < ActiveRecord::Base
  include Searchable
  
  has_many    :contacts, as: :contactable
  belongs_to  :family
  has_many    :parents, through: :family
  has_many    :schoolclass_students
  has_many    :schoolclasses, through: :schoolclass_students
  has_many    :teachers, -> { uniq }, through: :schoolclasses

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :family, presence: true

  ### candidate to move to module
  def first_last
    firstname + (nickname && (nickname.size > 0) ? " (#{nickname}) " : " ") + lastname
  end

  def last_first
    lastname + ", " + firstname + (nickname && (nickname.size > 0) ? " (#{nickname})" : "")
  end

  def family_siblings
    # this is an array of students within the student's family
    # who are not including the student themselves
    if self.family
      Student.where("family_id = ? AND id != ?", family_id, id)
    else
      nil
    end
  end

  def get_administrator
    # what user ID is allowed to administer (edit) this object
    return self.family.get_administrator unless self.family.nil?
    return nil
  end

end


app/controllers/schoolclasses_controller.rb
class SchoolclassesController < ApplicationController
  before_action :set_schoolclass, only: [:show, :edit, :update, :add_teachers, :add_students]
  before_action :require_user
  before_action :require_admin, only: [:new,  :create]
  before_action :require_creator_or_admin, only: [:edit, :update]

  def index
    @schoolclasses = Schoolclass.all.sort_by {|sc| sc.name}
  end

  def new
    @schoolclass = Schoolclass.new
  end

  def create
    @schoolclass = Schoolclass.new(schoolclass_params)

    if @schoolclass.save
      flash[:notice] = "Class #{@schoolclass.name} was created"

      ### TODO: figure out where to redirect.  Some admin screen?
      redirect_to schoolclasses_path
    else
      render :new
    end
  end

  def edit
    # setting @schoolclass is handled by before_action to set the schoolclass instance var
  end

  def update
    if @schoolclass.update(schoolclass_params)
      flash[:notice] = "The Class \"#{@schoolclass.name}\" was updated."
      redirect_to schoolclass_path(@schoolclass)
    else
      render :edit
    end
  end

  def show
  end


  def add_teachers
    # we need to set up state so that we can provide
    # a picklist of teachers, and those teachers
    # can be assigned to the class identified in the params
    # this is done in the before_action
  end

  def add_students
    # we need to set up state so that we can provide
    # a picklist of students, and those students
    # can be assigned to the class identified in the params
    # this is done in the before_action
  end

  def set_teachers
  end

  def set_students
  end
  
  private

  def schoolclass_params
    params.require(:schoolclass).permit(:name, teacher_ids: [], student_ids: [])
  end

  def set_schoolclass
    begin
      @schoolclass = Schoolclass.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:notice] = "There is no Class with ID #{params[:id]}.  Showing all classes instead."
      redirect_to schoolclasses_path
    end
  end
  
  def require_creator_or_admin
    access_denied(schoolclasses_path) unless allow_object_edit?(@schoolclass)
  end

  def require_admin
    access_denied(teachers_path) unless admin_logged_in?
  end

end

app/views/schoolclasses/_schoolclass_entry.html.erb
<% compact_var ||= "" %>

<% if compact_var == "compact" %>
  <p>
    <b><%= schoolclass_var.name %></b>
    <small><em style="margin-left: 20px;"><%= "With #{schoolclass_var.teachers.size} #{'teacher'.pluralize(schoolclass_var.teachers.size)} and #{schoolclass_var.students.size} #{'student'.pluralize(schoolclass_var.students.size)}" %></em></small>

    <%= icon_action_link("icon-list", "Details", schoolclass_path(schoolclass_var)) %>
    <% if allow_object_edit?(schoolclass_var) %>
      <%= icon_action_link("icon-pencil", "Edit", edit_schoolclass_path(schoolclass_var)) %>
    <% end %>
  </p>

<% else %>
  <div class="well">
    <h4><%= schoolclass_var.name %>
      <% if schoolclass_var.teachers.size > 0 && allow_object_edit?(schoolclass_var) %>
        <%= icon_action_link("icon-pencil", "Specify Teachers", add_teachers_schoolclass_path(schoolclass_var)) %>
      <% end %>
      <% if schoolclass_var.students.size > 0 && allow_object_edit?(schoolclass_var) %>
        <%= icon_action_link("icon-pencil", "Specify Students", add_students_schoolclass_path(schoolclass_var)) %>
      <% end %>
    </h4>
    <hr/>
    <div style="margin-left: 40px;">
      <h5><%= "Teacher".pluralize(schoolclass_var.teachers.size) %></h5>
      <% if schoolclass_var.teachers.size > 0 %>
        <%= render "teachers/teachers_list",
        {
          teacher_list_var: schoolclass_var.teachers,
          compact_var: "compact"
        } %>
      <% else %>
        <p>No teachers have been defined for this class.</p>
        <% if compact_var != "compact" && allow_object_edit?(schoolclass_var) %>
          <%= link_to '<i class="icon-plus"></i>Add Teachers'.html_safe, add_teachers_schoolclass_path(schoolclass_var), class: "btn btn-small" %>
        <% end %>
      <% end %>
    </div>

    <div style="margin-left: 40px;">
      <h5><%= "Student".pluralize(schoolclass_var.students.size) %></h5>
      <% if schoolclass_var.students.size > 0 %>
        <%= render "students/students_list",
        {
          student_list_var: schoolclass_var.students,
          compact_var: "compact"
        } %>
      <% else %>
        <p>No students have been defined for this class.</p>
        <% if compact_var != "compact" && allow_object_edit?(schoolclass_var) %>
          <%= link_to '<i class="icon-plus"></i>Add Students'.html_safe, add_students_schoolclass_path(schoolclass_var), class: "btn btn-small" %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>


app/views/schoolclasses/_schoolclass_form.html.erb
<%= render "shared/content_title", {title_var: title_var} %>

<% create_button_string = @schoolclass.new_record? ? "Create Class Record" : "Update Class Record" %>

<%= render "shared/errors_display", errors_set: @schoolclass.errors %>

<div class="well">

  <%= form_for @schoolclass do |f| %>
    <div class="control-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <br/>
    <%= f.submit create_button_string, class: "btn btn-primary" %>
  <% end %>

</div>

app/views/schoolclasses/_schoolclass_list.html.erb
<% allow_add_class_var ||= "" %>
<% warn_on_empty_var ||= "" %>

<div class="well">
  <% if schoolclass_list_var.size > 0 %>
    <% schoolclass_list_var.each do |sc| %>
      <%= render "schoolclasses/schoolclass_entry", 
        {
          schoolclass_var: sc,
          compact_var: "compact"
        } %>
      <hr/>
    <% end %>
  <% else %>
    <% if warn_on_empty_var == "warn" %>
      <p>
        No class information has been created yet.
        Would you like to add classes?
      </p>
    <% end %>
  <% end %>  

  <% if allow_add_class_var == "allow" %>
    <%= link_to '<i class="icon-plus"></i>Add Class'.html_safe, new_schoolclass_path, class: "btn btn-small" %>
  <% end %>

</div>

app/views/schoolclasses/add_students.html.erb
<div class="well">

  <%= form_for @schoolclass do |f| %>
    <div class="control-group">
      <%= f.label :student_ids, "Available Students" %>
      <%= f.collection_select(:student_ids, Student.all.sort_by{ |t| t.last_first }, :id, :last_first,
          {
            selected: @schoolclass.students.map(&:id)
          },
          {
            multiple: true,
            style: "width: 400px;",
            size: Student.all.size < 8 ? Student.all.size : 8
          }) %>
    </div>

    <br/>
    <%= f.submit "Set Students", class: "btn btn-primary" %>
  <% end %>

</div>

app/views/schoolclasses/add_teachers.html.erb
<div class="well">

  <%= form_for @schoolclass do |f| %>
    <div class="control-group">
      <%= f.label :teacher_ids, "Available Teachers" %>
      <%= f.collection_select(:teacher_ids, Teacher.all.sort_by{ |t| t.last_first }, :id, :last_first,
          {
            selected: @schoolclass.teachers.map(&:id)
          },
          {
            multiple: true,
            style: "width: 400px;",
            size: Teacher.all.size < 8 ? Teacher.all.size : 8
          }) %>
    </div>

    <br/>
    <%= f.submit "Set Teachers", class: "btn btn-primary" %>
  <% end %>

</div>

app/views/schoolclasses/edit.html.erb
<%= render "schoolclass_form", title_var: "Edit Class Details" %>

app/views/schoolclasses/index.html.erb
<%= render "shared/content_title", title_var: "Classes" %>
<%= render "schoolclasses/schoolclass_list",
    {
      schoolclass_list_var: @schoolclasses,
      allow_add_class_var: (admin_logged_in?  ? "allow" : ""),
      warn_on_empty_var: "warn",
      compact_var: "compact"
    } %>

app/views/schoolclasses/new.html.erb
<%= render "schoolclass_form", title_var: "Create new Class record" %>


app/views/schoolclasses/show.html.erb
<%= render "schoolclasses/schoolclass_entry", schoolclass_var: @schoolclass %>
