config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/freshuser', to: 'home#freshuser'
  get '/developer', to: 'home#developer'
  get '/search', to: 'home#search'
  get '/administer_families', to: 'home#administer_families'
  
  resources :families, except: [:destroy] do
    resources :parents, only: [:new, :create, :edit, :update]
    resources :students, only: [:new, :create, :edit, :update]
    resources :contacts, only: [:new, :create]
    resources :addresses, only: [:new, :create]

    collection do
      get "search"
    end
  end

  resources :parents, except: [:destroy, :new, :create] do
    resources :addresses, only: [:new, :create]
    resources :contacts, only: [:new, :create]

    collection do
      get "search"
    end
  end

  resources :contacts, only: [:edit, :update]
  resources :addresses, only: [:edit, :update]

  resources :students, except: [:destroy, :new, :create] do
    collection do
      get "search"
    end
  end

  resources :schoolclasses, except: [:destroy] do
    member do
      get "add_teachers"
      get "add_students"
      post "set_teachers"
      post "set_students"
    end
  end

  resources :teachers, except: [:destroy]

  resources :users, only: [:new, :show, :edit, :create, :update] do
    collection do
      get "admin_edit"
    end
  end

end

app/models/parent.rb
class Parent < ActiveRecord::Base
  include Searchable

  has_one     :address, as: :addressable
  has_many    :contacts, as: :contactable
  belongs_to  :family
  has_many    :students, through: :family

  validates :firstname, presence: true, length: {minimum: 1}
  validates :lastname, presence: true, length: {minimum: 1}
  
  def first_last
    firstname + " " + lastname
  end

  def last_first
    lastname + ", " + firstname
  end

  def get_administrator
    # what user ID is allowed to administer (edit) this object
    return self.family.get_administrator unless self.family.nil?
    return nil
  end
  
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_action :set_parent, only: [:show, :edit, :update]
  before_action :set_family_for_parent_creation, only: [:new, :create]
  before_action :require_user
  before_action :require_creator_or_admin, only: [:new, :create, :edit, :update]

  def index
    @parents = Parent.all.sort_by {|p| p.lastname}
  end

  def new
    @parent = Parent.new

    @parent.family = @family
    # we expect that we get routed here only as a subordinate of family
    # so we set the family of the parent
  end

  def create
    @parent = Parent.new(parent_params)
    @parent.family = @family  # @family is set in the before_action

    ## TODO: set the user ID of the family
    ## @family.owner = current_user_get

    if @parent.save
      flash[:notice] = "Parent #{@parent.first_last} was created"
      redirect_to parent_path(@parent)
    else
      render :new
    end
  end

  def edit
    # setting @parent is handled by before_action to set the parent instance var
  end

  def update
    if @parent.update(parent_params)
      flash[:notice] = "The parent \"#{@parent.first_last}\" was updated."
      redirect_to parent_path(@parent)
    else
      render :edit
    end
  end

  def show
  end

  private

  def parent_params
    params.require(:parent).permit(:firstname, :lastname)
  end

  def set_parent
    begin
      @parent = Parent.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:notice] = "There is no parent with ID #{params[:id]}.  Showing all parents instead."
      redirect_to parents_path
    end
  end

  def set_family_for_parent_creation
    if (params[:family_id])
      begin      
        @family = Family.find(params[:family_id])
      rescue ActiveRecord::RecordNotFound
        flash[:notice] = "There is no family with ID #{params[:family_id]}.  Cannot create a parent for an invalid Family Record."

        ### figure out if this is the right place to redirect
        redirect_to families_path
      end

    else
      # we did not have a family be specified
      flash[:notice] = "Attempt to create parent without providing a family identifier.  You must create a parent record for a specific family."

      ### figure out if this is the right place to redirect
      redirect_to families_path
    end
  end

  def require_creator_or_admin
    case
    when @parent.nil? && @family.nil?
      access_denied(parents_path)
    when @parent.nil?
      access_denied(parents_path) unless allow_object_edit?(@family)
    else
      access_denied(parents_path) unless allow_object_edit?(@parent)
    end
  end

end

app/views/parents/_parent_entry.html.erb
<% allow_add_contact_var ||= "" %>
<% allow_add_address_var ||= "" %>
<% warn_on_empty_var ||= "" %>
<% family_var ||= nil %>
<% compact_var ||= "" %>
<% name_method ||= :first_last %>

<% if compact_var == "compact" %>
  <p>
    <b><%= parent_var.send(name_method) %></b>
    <% if family_var.nil? %>
      <!-- family_var being nil means that we are not listing the parent in the -->
      <!-- context of a family listing and therefore OK to show more editing controls -->
      <% if allow_object_edit?(parent_var) %>
        <%= icon_action_link("icon-pencil", "Edit", edit_parent_path(parent_var)) %>
      <% end %>
      <%= icon_action_link("icon-home", "Family", family_path(parent_var.family)) %>
      <%= icon_action_link("icon-user", "Details", parent_path(parent_var)) %>
    <% else %>
      <%= icon_action_link("icon-user", "Details", parent_path(parent_var)) %>
    <% end %>
  </p>

<% else %>
  <% if family_var.nil? %>
    <div class="well">
  <% end %>
    <h4><%= parent_var.send(name_method) %>
    <% if family_var.nil? %>
      <!-- family_var being nil means that we are not listing the parent in the -->
      <!-- context of a family listing and therefore OK to show more editing controls -->
      <% if allow_object_edit?(parent_var) %>
        <%= icon_action_link("icon-pencil", "Edit", edit_parent_path(parent_var)) %>
      <% end %>
      <%= icon_action_link("icon-home", "Family", family_path(parent_var.family)) %>
    <% else %>
      <%= icon_action_link("icon-user", "Details", parent_path(parent_var)) %>
    <% end %>
    </h4>

    <div style="margin-left: 40px;">
      <% if parent_var.contacts.size > 0 %>
        <table class="well table table-condensed">
          <tr>
            <th>Contact Type</th>
            <th>Info</th>
            <% if allow_object_edit?(parent_var) %>
              <th>Actions</th>
            <% end %>
          </tr>

          <% parent_var.contacts.each do |contact| %>
            <tr>
              <td><%= contact.contact_type %></td>
              <td><%= contact.contact_data %></td>
              <% if allow_object_edit?(parent_var) %>
                <td><%= icon_action_link("icon-pencil", "Edit", edit_contact_path(contact)) %></td>
              <% end %>
            </tr>
          <% end %> <!-- contacts iteration -->
        </table>
      <% else %>
        <% if warn_on_empty_var == "warn" %>
          <p>
            No contact information has been created yet.
            <% if allow_object_edit?(parent_var) %>
              Would you like to add a contact to this parent?  
            <% else %>
              <em class="quiet">You do not have permissions to modify contact information for this parent.</em>
            <% end %>
          </p>
        <% end %>
      <% end %> <!-- any contacts for the person -->

      <% if allow_add_contact_var == "allow" && allow_object_edit?(parent_var) %>
        <%= link_to '<i class="icon-plus"></i>Add Contact'.html_safe, new_parent_contact_path(parent_var), class: "btn btn-small" %>
      <% end %>
    </div>

    <hr/>

    <!-- display address info -->
    <div style="margin-left: 40px;">
      <% if parent_var.address  && allow_object_edit?(parent_var) %>
        <h5><em>Parent Address</em><%= icon_action_link("icon-pencil", "Edit", edit_address_path(parent_var.address)) %></h5>
          <%= render "addresses/address_entry", {address_var: parent_var.address, size_var: "small"} %>
      <% else %>
        <% if warn_on_empty_var == "warn" %>
          <% if parent_var.family.address.nil? %>
            <p>
              No address information has been created yet.
              <% if allow_object_edit?(parent_var) %>
                Would you like to add an address to this parent?  
              <% else %>
                <em class="quiet">You do not have permissions to modify address information for this parent.</em>
              <% end %>
            </p>
          <% else %>
            <p>
              No address information has been created yet,
              however the Parent's family already has an address.
            </p>
          <% end %>
        <% end %>

        <!-- unlike contacts, we only have one address per parent -->
        <% if allow_add_address_var == "allow" && allow_object_edit?(parent_var) %>
          <%= link_to '<i class="icon-plus"></i>Add Address'.html_safe, new_parent_address_path(parent_var), class: "btn btn-small" %>
        <% end %>
      <% end %>
    </div>
  <% if family_var.nil? %>
    </div>
  <% end %>
<% end %>

app/views/parents/_parent_form.html.erb
<%= render "shared/content_title", {title_var: title_var} %>

<% create_button_string = @parent.new_record? ? "Create Parent Record" : "Update Parent Record" %>

<%= render "shared/errors_display", errors_set: @parent.errors %>

<div class="well">

  <%= form_for [@parent.family, @parent] do |f| %>
    <div class="control-group">
      <%= f.label :firstname %>
      <%= f.text_field :firstname %>
    </div>

    <div class="control-group">
      <%= f.label :lastname %>
      <%= f.text_field :lastname %>
    </div>

    <br/>
    <%= f.submit create_button_string, class: "btn btn-primary" %>
  <% end %>

</div>

app/views/parents/_parents_list.html.erb
<% allow_add_parent_var ||= "" %>
<% warn_on_empty_var ||= "" %>
<% family_var ||= nil %>
<% compact_var ||= "" %>
<% name_method ||= :first_last %>

<div class="well">
  <% if parent_list_var.size > 0 %>
    <% parent_list_var.each do |p| %>
      <%= render "parents/parent_entry", {parent_var: p, family_var: family_var, compact_var: compact_var, name_method: name_method} %>
    <% end %>  <!-- parent iteration --> 
  <% else %>
    <% if warn_on_empty_var == "warn" && family_var %>
      <p>
        No parent information has been created yet.
        <% if allow_add_parent_var == "allow" %>
          Would you like to add parents to this family?  
        <% else %>
          <em class="quiet">You do not have permissions to modify parent information.</em>
        <% end %>
      </p>
    <% end %>
  <% end %>

  <% if allow_add_parent_var == "allow" && family_var %>
    <%= link_to '<i class="icon-plus"></i>Add Parent'.html_safe, new_family_parent_path(family_var), class: "btn btn-small" %>
  <% end %>

</div>

app/views/parents/edit.html.erb
<%= render "parent_form", title_var: "Edit Parent Details" %>

app/views/parents/index.html.erb
<%= render "shared/content_title", title_var: "Parents" %>
<%= render "parents/parents_list",
    {
      parent_list_var: @parents,
      name_method: :last_first,
      allow_add_parent_var: "",
      warn_on_empty_var: "",
      family_var: nil,
      compact_var: "compact"
    } %>

app/views/parents/new.html.erb
<%= render "parent_form", title_var: "Create new Parent record" %>


app/views/parents/show.html.erb
<%= render "parents/parent_entry",
      {
        parent_var: @parent,
        allow_add_contact_var: "allow",
        allow_add_address_var: "allow",
        warn_on_empty_var: "warn",
      }
 %>
