config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/freshuser', to: 'home#freshuser'
  get '/developer', to: 'home#developer'
  get '/search', to: 'home#search'
  get '/administer_families', to: 'home#administer_families'
  
  resources :families, except: [:destroy] do
    resources :parents, only: [:new, :create, :edit, :update]
    resources :students, only: [:new, :create, :edit, :update]
    resources :contacts, only: [:new, :create]
    resources :addresses, only: [:new, :create]

    collection do
      get "search"
    end
  end

  resources :parents, except: [:destroy, :new, :create] do
    resources :addresses, only: [:new, :create]
    resources :contacts, only: [:new, :create]

    collection do
      get "search"
    end
  end

  resources :contacts, only: [:edit, :update]
  resources :addresses, only: [:edit, :update]

  resources :students, except: [:destroy, :new, :create] do
    collection do
      get "search"
    end
  end

  resources :schoolclasses, except: [:destroy] do
    member do
      get "add_teachers"
      get "add_students"
      post "set_teachers"
      post "set_students"
    end
  end

  resources :teachers, except: [:destroy]

  resources :users, only: [:new, :show, :edit, :create, :update] do
    collection do
      get "admin_edit"
    end
  end

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Family Directory", families_path, :class => 'brand' %>
  </li>
</ul>

<% if logged_in? %>
	<div class="btn-group nav_item">
	  <%= link_to "Create New Family", new_family_path, class: "btn btn-success btn-small", style: "padding-bottom: 6px;" %>
	</div>

	<div class="btn-group nav_item">
		<%= link_to "#", class: "btn btn-small dropdown-toggle", "data-toggle" => "dropdown", style: "padding-bottom: 6px;" do %>
		Directory Listings <span class="caret"></span>
		<% end %>
		<ul class="dropdown-menu">
			<% menulist = [
					["Family Directory", families_path],
					["Parent Directory", parents_path],
					["Student Directory", students_path],
					["Teacher Directory", teachers_path],
					["Classes Directory", schoolclasses_path]
					] %>

			<% menulist.each do |ml| %>
				<li>
					<%= link_to ml[0], ml[1] %>
				</li>
			<% end %>
		</ul>
	</div>
	
	<div class="btn-group nav_item">
	  <%= link_to(search_path) do %>
	  	<span class="btn btn-primary"><i class="icon-search" style="padding-right: 4px;"></i>
	  	Search</span>
  	<% end %>
  </div>

	<div class="btn-group nav_item">
		<%= link_to "#", class: "btn btn-small dropdown-toggle", "data-toggle" => "dropdown", style: "padding-bottom: 6px;" do %>
			<%= ("&nbsp;" + current_user_get.username + "&nbsp;&nbsp;").html_safe %><span class="caret"></span>
		<% end %>

		<ul class="dropdown-menu">
			<li>
				<%= link_to(edit_user_path(current_user_get)) do %>
					<i class='icon-pencil'></i>
					Edit Profile
				<% end %>
			</li>
			<li>
				<%= link_to(user_path(current_user_get)) do %>
					<i class='icon-user'></i>
					View Profile
				<% end %>
			</li>
			<li>
				<%= link_to(logout_path) do %>
					<i class='icon-circle-arrow-left'></i>
					Logout
				<% end %>
			</li>
		</ul>
	</div>

	<div class="btn-group nav_item">
	  <%= link_to(freshuser_path) do %>
	  	<span class="btn btn-info"><i class="icon-question-sign" style="padding-right: 4px;"></i>
	  	Help</span>
  	<% end %>
  </div>

<% end %>



<% if false %>

	<div class="nav_item">
	  <%= link_to "Create New Post", new_post_path, class: "btn btn-success btn-small" %>
	</div>


	<div class="btn-group nav_item">
		<%= link_to "#", class: "btn btn-small dropdown-toggle", "data-toggle" => "dropdown" do %>
			<i class="icon-search"></i>
			&nbsp;Search&nbsp;&nbsp;<span class="caret"></span>
		<% end %>

		<ul class="dropdown-menu">
			<li>
			  <%= link_to(search_users_path) do %>
			  	<i class="icon-user"></i>
			  	Search Users
			  <% end %>
			</li>
			<li>
			  <%= link_to(search_posts_path) do %>
				  <i class="icon-inbox"></i>
				  Search Posts
			  <% end %>
			</li>
		</ul>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
<!--    ygurevich: 10/7/2014: removing the viewport to test out html -->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
    <title>School Directory</title>
    <meta name="description" content="">
    <meta name="author" content="Yevgeny Gurevich">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container-fluid">
         <div class="row-fluid">
          <div class="well-fluid">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>